dependencies {
    constraints {
        api("cn.jaylong:lab-autoconfig-gradle-kt:${properties["version"]}")
        api("cn.jaylong:lab-axon-gradle-kt:${properties["version"]}")
        api("cn.jaylong:lab-core-gradle-kt:${properties["version"]}")
        api("cn.jaylong:lab-data-jpa-gradle-kt:${properties["version"]}")
        api("cn.jaylong:lab-mq-gradle-kt:${properties["version"]}")
        api("cn.jaylong:lab-security-gradle-kt:${properties["version"]}")
        api("cn.jaylong:lab-snowflake-gradle-kt:${properties["version"]}")
        api("cn.jaylong:lab-web-gradle-kt:${properties["version"]}")
//        // core
        api("org.jetbrains.kotlin:kotlin-reflect:${properties["kotlin-reflect-version"]}")
        api("cn.hutool:hutool-all:${properties["hutool-version"]}")
        api("org.projectlombok:lombok:${properties["lombok-version"]}")
        api("com.alibaba:fastjson:${properties["fastjson-version"]}")
        api("org.springframework.boot:spring-boot-starter-freemarker:${properties["springboot-version"]}")
        api("org.springframework.boot:spring-boot-starter-thymeleaf:${properties["springboot-version"]}")
        api("org.springframework.boot:spring-boot-starter-validation:${properties["springboot-version"]}")
        api("org.springframework.boot:spring-boot-starter:${properties["springboot-version"]}")
        api("org.springframework.boot:spring-boot-starter-test:${properties["springboot-version"]}")
        api("org.springframework.boot:spring-boot-autoconfigure:${properties["springboot-version"]}")
        api("org.springframework.boot:spring-boot-configuration-processor:${properties["springboot-version"]}")
        api("org.springframework.cloud:spring-cloud-starter-bootstrap:${properties["spring-cloud-starter-version"]}")
        api("org.springframework.cloud:spring-cloud-starter:${properties["spring-cloud-starter-version"]}")
        api("org.springframework.boot:spring-boot-gradle-plugin:${properties["spring-boot-gradle-plugin-version"]}")
        api("org.apache.httpcomponents:httpclient:${properties["httpclient-version"]}")
        api("com.tngtech.archunit:archunit:${properties["archunit-version"]}")
        api("org.mapstruct:mapstruct:${properties["mapstruct-version"]}")
        api("org.mapstruct:mapstruct-processor:${properties["mapstruct-version"]}")
        api("javax.annotation:javax.annotation-api:${properties["javax.annotation-api-version"]}")
        api("junit:junit:${properties["junit-version"]}")
        api("org.junit.jupiter:junit-jupiter-api:${properties["junit-jupiter-version"]}")
        api("org.junit.jupiter:junit-jupiter-engine:${properties["junit-jupiter-version"]}")
        api("org.jetbrains.kotlinx:kotlinx-datetime:${properties["kotlinx-datetime-version"]}")
        api("org.jetbrains.kotlinx:kotlinx-serialization-json:${properties["kotlinx-serialization-json-version"]}")
        // data-jpa
        api("com.querydsl:querydsl-apt:${properties["queryds-version"]}")
        api("com.querydsl:querydsl-apt:${properties["queryds-version"]}:jpa")
        api("com.querydsl:querydsl-jpa:${properties["queryds-version"]}")
        api("com.querydsl:querydsl-sql-codegen:${properties["queryds-version"]}")
        api("org.hibernate.javax.persistence:hibernate-jpa-2.1-api:${properties["hibernate-jpa-2.1-api-version"]}")
        api("com.vladmihalcea:hibernate-types-55:${properties["hibernate-types-55-verison"]}")
        api("org.postgresql:postgresql:${properties["postgresql-version"]}")
        api("org.springframework.boot:spring-boot-starter-data-jpa:${properties["springboot-version"]}")
        api("jakarta.persistence:jakarta.persistence-api:${properties["jakarta.persistence-api-version"]}")
        api("javax.persistence:javax.persistence-api:${properties["javax.persistence-api-version"]}")
        api("com.cosium.spring.data:spring-data-jpa-entity-graph:${properties["spring-data-jpa-entity-graph-version"]}")
        // web
        api("com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery:${properties["nacos-cloud-version"]}")
        api("com.alibaba.nacos:nacos-client:${properties["nacos-client-version"]}")
        api("com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config:${properties["nacos-cloud-version"]}")
        api("org.springframework.boot:spring-boot-starter-web:${properties["springboot-version"]}")
        api("io.springfox:springfox-boot-starter:${properties["springfox-version"]}")
        api("org.springframework.boot:spring-boot-starter-undertow:${properties["springboot-version"]}")
        // axon
        api("org.axonframework:axon-modelling:${properties["axon-framework-version"]}")
        api("org.axonframework:axon-spring-boot-starter:${properties["axon-framework-version"]}")
        api("org.axonframework:axon-test:${properties["axon-framework-version"]}")
        // mq
        api("org.springframework.kafka:spring-kafka:${properties["spring.kafka-version"]}")
        // security
        api("org.springframework.boot:spring-boot-starter-security:${properties["springboot-version"]}")
        api("org.springframework.security:spring-security-oauth2-resource-server:${properties["spring-security-oauth2-resource-server-version"]}")
        api("org.springframework.security:spring-security-oauth2-jose:${properties["spring-security-oauth2-jose-version"]}")
        api("javax.servlet:javax.servlet-api:${properties["javax.servlet-api-version"]}")
    }
}
